### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/pyeti#8]
This lib is simple and the migration shouldn't be too difficult.

**Comment by threathive** [comment]
I am happy to take a crack at this. I am already porting it for my own use at the moment.

**Comment by tomchop** [comment]
Excellent, thanks!

**Comment by threathive** [comment]
Let me know if the current pull request isn't what your looking for and I can do more there.

**Comment by dadokkio** [comment]
Hi, are you going to update also the package on pypi?

**Comment by sebdraven** [comment]
for the moment we are finishing the migration with a beta version. After this time of the beta, we release it.

**Comment by sebdraven** [comment]
The lib is full py3
